version: '3.8'
services:
    postgres:
        image: postgres:15.3
        volumes:
        - ./postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        environment:
            TZ: Asia/Shanghai
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Forever0.
            POSTGRES_DB: postgres
    app:
        image: ghcr.io/pzpupu/openai-proxy:1.2
        volumes:
          - type: bind
            source: ./.env   #这个是宿主机的地址
            target: /app/.env  #这个是容器里配置文件的地址
        ports:
            - "8080:8080"
        environment:
            TZ: Asia/Shanghai
        depends_on:
            - postgres