version: '3.8'
services:
    postgres:
        image: postgres:15.3
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        environment:
            TZ: Asia/Shanghai
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Forever0.
            POSTGRES_DB: postgres
    app:
        image: ghcr.io/pzpupu/openai-proxy:1.0
        ports:
            - "8080:8080"
        environment:
            TZ: Asia/Shanghai
        depends_on:
            - postgres